/*

 MAP_TEXT_EDITOR.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\malbe\Desktop\Backup\Gameboy Development\Sluice Juice Studios\Telestrations\assets\sprite_text.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_text_editorWidth 20
#define map_text_editorHeight 18
#define map_text_editorBank 0

extern unsigned char map_text_editor[];

/* End of MAP_TEXT_EDITOR.H */
