/*

 MAP_PLAYER_SELECT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\malbe\Desktop\Backup\Gameboy Development\Sluice Juice Studios\Telestrations\assets\sprite_text.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_player_selectWidth 20
#define map_player_selectHeight 18
#define map_player_selectBank 0

extern unsigned char map_player_select[];

/* End of MAP_PLAYER_SELECT.H */
